export const diatonic = ['C', 'D', 'E', 'F', 'G', 'A', 'B'];
export const sharped = ['C#', 'D#', 'F#', 'G#', 'A#'];
export const flated = ['Db', 'Eb', 'Gb', 'Ab', 'Bb'];

export const TYPE_MAJOR = "major";
export const TYPE_MINOR = "minor";
export const TYPE_DIMINISHED = "diminished";
export const TYPE_AUGMENTED = "augmented";
export const TYPE_SUSPENDEDTWO = "suspended2";
export const TYPE_SUSPENDEDFOUR = "suspended4";
export const TYPE_SCALE = "scale";
export const TYPE_CHORD = "chord";
export const TYPE_NOTE = "note";
export const TYPE_SHARPED = "sharped";
export const TYPE_FLATED = "flated";
export const TYPE_NONE = "none";
export const TYPE_7TH = "7";
export const TYPE_9TH = "9";
export const TYPE_ADD9 = "add9";
